name: build-exe
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install opencv-python pillow numpy pandas qrcode pyinstaller pyzbar

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --windowed ^
            --name=JPG_Barcode_Renamer ^
            --add-data "desktop_app.py;." ^
            --add-data "barcode_processor.py;." ^
            --hidden-import=tkinter ^
            --hidden-import=cv2 ^
            --hidden-import=PIL ^
            --hidden-import=pandas ^
            --hidden-import=numpy ^
            --hidden-import=qrcode ^
            --hidden-import=pyzbar ^
            desktop_app.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: JPG_Barcode_Renamer
          path: dist/JPG_Barcode_Renamer.exe
